# Generated by Django 5.0.3 on 2024-03-18 10:16

import activities_app.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gamification_app', '0009_alter_rewards_banner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('postUrl', models.FileField(upload_to=activities_app.models.user_directory_path)),
                ('like_count', models.BigIntegerField(default=0)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('tags', models.CharField(blank=True, max_length=100)),
                ('active', models.BooleanField(default=True)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='gamification_app.sustainableaction')),
                ('likes', models.ManyToManyField(blank=True, default=None, related_name='like', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
