# Generated by Django 4.0.4 on 2023-07-01 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Co2_assumption',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='Co2',
            field=models.FloatField(default=0),
        ),
    ]
