# Generated by Django 4.0.4 on 2023-06-21 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rewards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=200)),
                ('banner', models.ImageField(blank=True, null=True, upload_to='banner/')),
                ('title', models.CharField(max_length=25)),
                ('description', models.CharField(max_length=100)),
                ('coinrequired', models.BigIntegerField()),
                ('redeemed_count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SustainableActionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SustainableAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('points', models.PositiveIntegerField()),
                ('impact', models.CharField(max_length=200)),
                ('savedemmision', models.IntegerField(default=0)),
                ('color', models.CharField(max_length=11)),
                ('image', models.ImageField(blank=True, null=True, upload_to='sustainable_action_images/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamification_app.sustainableactioncategory')),
            ],
        ),
    ]
