# Generated by Django 4.0.4 on 2023-09-13 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rewards',
            name='title',
            field=models.CharField(max_length=500),
        ),
    ]
