# Generated by Django 4.0.4 on 2023-09-15 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification_app', '0002_alter_rewards_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rewards',
            name='banner',
            field=models.FileField(blank=True, null=True, upload_to='banner/'),
        ),
    ]
