# Generated by Django 4.0.4 on 2023-09-15 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_user_bio_alter_user_phone_number_and_more'),
        ('gamification_app', '0003_alter_rewards_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rewards',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='base.company'),
        ),
    ]
