# Generated by Django 4.0.4 on 2023-09-22 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification_app', '0005_alter_sustainableaction_savedemmision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sustainableaction',
            name='savedemmision',
            field=models.IntegerField(default=0),
        ),
    ]
