# Generated by Django 4.0.4 on 2023-10-02 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification_app', '0006_alter_sustainableaction_savedemmision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rewards',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='banner/'),
        ),
    ]
