# Generated by Django 4.0.4 on 2023-10-02 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification_app', '0007_alter_rewards_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rewards',
            name='banner',
            field=models.FileField(blank=True, null=True, upload_to='banner/'),
        ),
    ]
