# Generated by Django 4.0.4 on 2023-10-05 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification_app', '0008_alter_rewards_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rewards',
            name='banner',
            field=models.URLField(blank=True, null=True),
        ),
    ]
